load_avatarmodule_checkpoint: 'checkpoints/avatar_zyx/latest'
gpu_ids: [0]

dataset:
  dataroot: 'demo_dataset'
  video_name: 'zyx/eval'
  resolution: 512

avatarmodule:
  exp_dim_2d: 256
  encoder_dims: [3, 32, 64, 128, 256]
  mapping_dims: [256, 256, 256, 128]
  headmodule:
    triplane_res: 256
    triplane_dim: 32
    exp_dim_3d: 128
    density_mlp: [32, 128, 1]
    color_mlp: [59, 128, 32]
    view_freq: 4
    noise: 0.01
    bbox: [[-1.5, 1.5], [-1.8, 1.8], [-1.9, 1.1]]
  upsampler_capacity: 32
  
neuralcamera:
  model_bbox: [[-1.5, 1.5], [-1.8, 1.8], [-1.9, 1.1]]
  image_size: 512
  N_samples: 64


recorder:
  name: 'self_reenactment_zyx'
  result_path: 'results'
